//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalladiumRecords.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NextOfKin
    {
        public long NextOfKinID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Age { get; set; }
        public string County { get; set; }
        public string SubCounty { get; set; }
        public string Ward { get; set; }
        public string Village { get; set; }
        public string CellPhone { get; set; }
        public string Email { get; set; }
        public string AlternativeCellNumber { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
        public Nullable<long> EnrollmentNumber { get; set; }
    }
}
